[project]
name="livenet"
version="0.1"

[tool.pytest.ini_options]
#pythonpath = ["serhii_libs"]
# testpaths = ["./tests/unit"]
python_files = ["*.py"]
log_cli = true
filterwarnings = ["ignore:::.*dateutil*", "ignore:::.*importlib*"]
addopts = "--ignore ./old"

